apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cm1.fullname" . }}-config-map
  labels:
    app: {{ template "cm1.name" . }}
    chart: {{ template "cm1.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
    key1: "value1"
